### PR TITLE
Switch to CMake

### PR DESCRIPTION
**Pull request by glx22**
This is based on @PeterN cmake branch.
I added MinGW and MSVC support, and done some cleaning.

### CODE REVIEW

**Review by TrueBrain — DISMISSED** [review]
I tried to find something to complain about, but I cannot.

It compiles for me.
It compiles for you.

Ship it!

(really, this is too big to really evaluate, and it looks fine on the surface, you are a smart guy, I think we will be fine :D)

**Review by TrueBrain — APPROVED** [review]
Still going to YOLO this as .. yeah, I love that you took the effort :D

**Comment by glx22** [comment]
When testing https://github.com/glx22/grfcodec/pull/2 I found some issues in this PR.

**Comment by Eddi-z** [comment]
Seems to work for me, needs updates to `readme.txt`, `0compiling.txt` and `.gitignore`

**Comment by matthijskooijman** [comment]
When switching to cmake, the documentation (0compile.txt) was not updated and still references the plain Makefile targets. Maybe it should be updated? It should probably also mention that, for a release build, you should run `cmake . -DCMAKE_BUILD_TYPE=Release` (without that, you get a debug build without optimizations), or the default build type [could be made release maybe](https://stackoverflow.com/a/41361741/740048).

**Pull request merged**
